SUCCESS: SUCCESS
FAILURE: FAILURE
MESSAGE:
  SUCCESS:
    POST: PROFILE SUCCESSFULLY CREATED
    GET: PROFILE SUCCESSFULLY FOUND
    PUT: PROFILE SUCCESSFULLY UPDATED
  FAILURE:
    POST: PROFILE NOT CREATED
    GET: PROFILE NOT FOUND
    PUT: PROFILE NOT UPDATED
EXCEPTION:
  NOT_FOUND: REQUESTED RESOURCE NOT FOUND
  PARTIAL_DATA: NEW PROFILE CANNOT BE PARTIALLY UPDATED
